#!/bin/bash

data=( `ps aux | grep -i dropbear | awk '{print $2}'`);

echo "----------------------";
echo "    DROPBEAR LOGIN    ";
echo "----------------------";

for PID in "${data[@]}"
do
#echo "check $PID";
	NUM=`cat /var/log/auth.log | grep -i openvpn | grep -i "Password auth succeeded" | grep "openvpn\[$PID\]" | wc -l`;
	USER=`cat /var/log/auth.log | grep -i openvpn | grep -i "Password auth succeeded" | grep "openvpn\[$PID\]" | awk '{print $10}'`;
	IP=`cat /var/log/auth.log | grep -i openvpn | grep -i "Password auth succeeded" | grep "openvpn\[$PID\]" | awk '{print $12}'`;
	if [ $NUM -eq 1 ]; then
		echo "$PID - $USER - $IP";
	fi
done

echo "";
